# Flags meaning
# -g is for debugging
# -c compiles files but doesn't link them (This is neccessary, Unsure why.)

# CFLAGS = -I libs/include -L libs/lib -o main test.cpp -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -Wall -fsanitize=undefined
CC = g++
fileName = noise.cpp

hello:
	echo "Hello, World"

build: 
	g++ $(fileName) -o out.exe
	.\out.exe

cube:
	$(CC) -c test_sfml.cpp -I libs/include -DSFML_STATIC
	$(CC) test_sfml.o -o test_sfml -L libs/lib -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lwinmm -lgdi32
	test_sfml


smain:
	$(CC) -c main_sfml.cpp -I libs/include -DSFML_STATIC
	$(CC) main_sfml.o -o main_sfml -L libs/lib -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lwinmm -lgdi32
	.\main_sfml

# The true main
testmain:
	$(CC) -c main_sfml.cpp -I libs/include -DSFML_STATIC -static 
	$(CC) main_sfml.o -o main_sfml -L libs/lib -lsfml-graphics-d -lsfml-window-s-d -lsfml-system-d -lopengl32 -lwinmm -lgdi32 -static
	.\main_sfml

fakemain:
	$(CC) main.cpp -o out.exe
	.\out.exe

practice3:
	$(CC) practice3.cpp -o practice3.exe
	.\practice3.exe

noise:
	$(CC) -c noise.cpp -I libs/include -DSFML_STATIC -static 
	$(CC) noise.o -o noise -L libs/lib -lsfml-graphics-d -lsfml-window-s-d -lsfml-system-d -lopengl32 -lwinmm -lgdi32 -static
	.\noise

clean:
